### ISSUE TITLE
Avoid dependency on Openfontlibrary.org for Amiri typeface

### ISSUE THREAD

**Issue by a3f** [osdev4arab/osdev4arab.github.io#5]
b9d8656

The main font (Amiri; like the default font for the bookpress) was being hosted on openfontlibrary.org. This website is currently offline.

Measures should be taken to either: 
a) Use another font completely (Unfortunate, Font looks kinda good)
b) Make the font downloadable from github instead of openfontlibrary (Bad for caching)
c) Leave openfontlibrary intact and default back after a set amount of unresponsiveness to a locally hosted version of it or to a complete alternative.

Trello entry: https://trello.com/c/mv1ltSFS/26-avoid-dependency-on-openfontlibrary-org-for-the-amiri-typeface

**Comment by KarimAllah** [comment]
@a3f Can we close this one now ? https://github.com/osdev4arab/osdev4arab.github.io/commit/a116fdef970a2c46bc4743172dcf99f9d380471a

**Comment by a3f** [comment]
I'd rather had a local version here as a fall-back, but I guess, if Google goes offline, that won't be our only problem.
Closing the issue.
